name: Create Repository

on:
  workflow_dispatch:

jobs:
  create_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Create Repository
      uses: actions/create-repo@v1
      with:
        name: introduction-to-github
        description: A repository for learning the basics of GitHub
        private: 'false'
